INSERT INTO PROPERTY (DATASET_ID, NAME, VALUE, INSERTED, UPDATED)
    VALUES  (1,'TEST_NAME','TEST_VALUE',FALSE,FALSE),
            (2,'TEST_NAME_2','TEST_VALUE_2',FALSE,FALSE);

INSERT INTO PROPERTY (DATASET_ID, NAME, VALUE, INSERTED, UPDATED)
    VALUES  (3,'TEST_NAME_3','TEST_VALUE_3',FALSE,FALSE),
            (4,'TEST_NAME_4','TEST_VALUE_4',FALSE,FALSE);


    